sudo: false

language: go
go:
  - "1.11.x"
  - "1.12.x"
  - "1.x"
env:
  - GO111MODULE=on

before_install:
  - go get -u golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover

script:
  - golint ./...
  - go vet ./...
  - go test -covermode=count -coverprofile=profile.cov ./...

notifications:
  email: false